// apps/viz-scope-link/src/components/VisibilityChip.tsx
import { Button } from "@/components/ui/button";
import { NodeTypeIcon } from "@/components/icons/NodeTypeIcon";
import { NodeType } from "@/lib/types";
import { cn } from "@/lib/utils";

interface VisibilityChipProps {
  type: NodeType;
  isVisible: boolean;
  isDisabled: boolean;
  onClick: () => void;
  className?: string;
}

export function VisibilityChip({ type, isVisible, isDisabled, onClick, className }: VisibilityChipProps) {
  return (
    <Button
      variant="outline"
      size="sm"
      onClick={onClick}
      disabled={isDisabled}
      aria-pressed={isVisible}
      aria-disabled={isDisabled}
      className={cn(
        "h-8 px-3 text-xs font-medium transition-all duration-150 gap-1.5",
        isVisible
          ? "bg-[hsl(var(--chip-visible-bg))] border-[hsl(var(--chip-visible-border))] text-[hsl(var(--chip-visible-text))] hover:brightness-110"
          : "bg-transparent border-border text-muted-foreground opacity-60 hover:opacity-80",
        isDisabled && "opacity-70 cursor-not-allowed",
        className
      )}
    >
      <NodeTypeIcon type={type} className="w-3.5 h-3.5" />
      {type}
    </Button>
  );
}

// apps/viz-scope-angular/src/app/shared/components/visibility-chip.component.ts
/**
 * Visibility Chip Component
 * Shows a node type with visibility toggle
 */

import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { NodeType } from '../../models';

@Component({
  selector: 'app-visibility-chip',
  standalone: true,
  imports: [CommonModule],
  template: `
    <button
      type="button"
      [disabled]="isDisabled"
      [attr.aria-pressed]="isVisible"
      [attr.aria-disabled]="isDisabled"
      (click)="handleClick()"
      [class]="buttonClasses"
    >
      <!-- Icon placeholder -->
      <span class="w-3.5 h-3.5 rounded-sm bg-current opacity-60"></span>
      <span>{{ type }}</span>
    </button>
  `,
  styles: [
    `
      :host {
        display: inline-block;
      }
    `,
  ],
})
export class VisibilityChipComponent {
  @Input() type!: NodeType;
  @Input() isVisible = true;
  @Input() isDisabled = false;

  @Output() chipClick = new EventEmitter<void>();

  get buttonClasses(): string {
    const classes = [
      'h-8 px-3 text-xs font-medium transition-all duration-150 gap-1.5',
      'flex items-center rounded-md border',
    ];

    if (this.isVisible) {
      classes.push(
        'bg-blue-50 dark:bg-blue-950',
        'border-blue-300 dark:border-blue-700',
        'text-blue-900 dark:text-blue-100',
        'hover:brightness-110'
      );
    } else {
      classes.push(
        'bg-transparent',
        'border-gray-300 dark:border-gray-700',
        'text-gray-500 dark:text-gray-400',
        'opacity-60 hover:opacity-80'
      );
    }

    if (this.isDisabled) {
      classes.push('opacity-70 cursor-not-allowed');
    } else {
      classes.push('cursor-pointer');
    }

    return classes.join(' ');
  }

  handleClick(): void {
    if (!this.isDisabled) {
      this.chipClick.emit();
    }
  }
}
