// apps/viz-scope-angular/src/app/features/runtime/components/floating-dock.component.ts
/**
 * Floating Dock Component
 * Floating toolbar for pan/select tools and undo/redo
 */

import {
  Component,
  Input,
  OnChanges,
  SimpleChanges,
  signal,
  effect,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatTooltipModule } from '@angular/material/tooltip';
import * as go from 'gojs';

export type ToolMode = 'pan' | 'select';

@Component({
  selector: 'app-floating-dock',
  standalone: true,
  imports: [CommonModule, MatButtonModule, MatIconModule, MatTooltipModule],
  template: `
    <div class="floating-dock">
      <!-- Pan button -->
      <button
        mat-icon-button
        [class.active]="toolMode() === 'pan'"
        [disabled]="!diagram"
        (click)="handlePanClick()"
        matTooltip="Pan (Hand tool)"
        aria-label="Pan tool"
      >
        <mat-icon>pan_tool</mat-icon>
      </button>

      <!-- Select button -->
      <button
        mat-icon-button
        [class.active]="toolMode() === 'select'"
        [disabled]="!diagram"
        (click)="handleSelectClick()"
        matTooltip="Select"
        aria-label="Select tool"
      >
        <mat-icon>mouse</mat-icon>
      </button>

      <!-- Separator -->
      <div class="separator"></div>

      <!-- Undo button -->
      <button
        mat-icon-button
        [disabled]="!canUndo()"
        (click)="handleUndo()"
        matTooltip="Undo"
        aria-label="Undo"
      >
        <mat-icon>undo</mat-icon>
      </button>

      <!-- Redo button -->
      <button
        mat-icon-button
        [disabled]="!canRedo()"
        (click)="handleRedo()"
        matTooltip="Redo"
        aria-label="Redo"
      >
        <mat-icon>redo</mat-icon>
      </button>
    </div>
  `,
  styles: [
    `
      .floating-dock {
        position: absolute;
        bottom: 16px;
        left: 50%;
        transform: translateX(-50%);
        z-index: 50;

        display: flex;
        align-items: center;
        gap: 6px;
        height: 44px;
        padding: 0 8px;
        border-radius: 9999px;

        background: rgba(255, 255, 255, 0.95);
        border: 1px solid rgba(0, 0, 0, 0.1);
        box-shadow:
          0 4px 6px -1px rgba(0, 0, 0, 0.1),
          0 10px 15px -3px rgba(0, 0, 0, 0.1);
        backdrop-filter: blur(8px);
      }

      :host-context(.dark) .floating-dock {
        background: rgba(31, 41, 55, 0.95);
        border-color: rgba(255, 255, 255, 0.1);
      }

      button {
        width: 36px;
        height: 36px;
        transition: all 150ms ease;

        mat-icon {
          font-size: 18px;
          width: 18px;
          height: 18px;
        }

        &.active {
          background-color: rgba(0, 0, 0, 0.08);
          color: rgba(0, 0, 0, 0.87);
        }

        &:not(.active):not(:disabled):hover {
          background-color: rgba(0, 0, 0, 0.04);
        }

        &:disabled {
          opacity: 0.4;
          cursor: not-allowed;
        }
      }

      :host-context(.dark) button {
        &.active {
          background-color: rgba(255, 255, 255, 0.12);
          color: rgba(255, 255, 255, 0.87);
        }

        &:not(.active):not(:disabled):hover {
          background-color: rgba(255, 255, 255, 0.08);
        }
      }

      .separator {
        width: 1px;
        height: 20px;
        background-color: rgba(0, 0, 0, 0.12);
        margin: 0 2px;
      }

      :host-context(.dark) .separator {
        background-color: rgba(255, 255, 255, 0.12);
      }
    `,
  ],
})
export class FloatingDockComponent implements OnChanges {
  @Input() diagram: go.Diagram | null = null;

  // Signals for reactive state
  toolMode = signal<ToolMode>('pan');
  canUndo = signal(false);
  canRedo = signal(false);

  private modelChangedListener: ((e: go.ChangedEvent) => void) | null = null;

  constructor() {
    // Effect to setup diagram listeners when diagram changes
    effect(
      () => {
        const diagram = this.diagram;
        if (!diagram) return;

        this.setupDiagram(diagram);
      },
      { allowSignalWrites: true }
    );
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['diagram']) {
      // Cleanup old listener
      if (
        this.modelChangedListener &&
        changes['diagram'].previousValue instanceof go.Diagram
      ) {
        const oldDiagram = changes['diagram'].previousValue as go.Diagram;
        oldDiagram.removeModelChangedListener(this.modelChangedListener);
      }

      // Setup new diagram
      if (this.diagram) {
        this.setupDiagram(this.diagram);
      }
    }
  }

  private setupDiagram(diagram: go.Diagram): void {
    // One-time initialization: enable infinite scroll
    diagram.commit((d) => {
      d.allowHorizontalScroll = true;
      d.allowVerticalScroll = true;
      d.scrollMode = go.Diagram.InfiniteScroll;
    }, 'init-scroll');

    // Set pan mode as default
    this.setPanMode(diagram);

    // Update cursor during panning
    const panTool = diagram.toolManager.panningTool;
    const originalDoMouseDown = panTool.doMouseDown;
    const originalDoMouseUp = panTool.doMouseUp;

    panTool.doMouseDown = function () {
      if (diagram.defaultCursor === 'grab') {
        const div = diagram.div as HTMLDivElement;
        div.style.cursor = 'grabbing';
      }
      originalDoMouseDown.call(this);
    };

    panTool.doMouseUp = function () {
      if (diagram.defaultCursor === 'grab') {
        const div = diagram.div as HTMLDivElement;
        div.style.cursor = 'grab';
      }
      originalDoMouseUp.call(this);
    };

    // Listen to model changes for undo/redo state
    this.modelChangedListener = () => {
      this.updateUndoRedoState(diagram);
    };
    diagram.addModelChangedListener(this.modelChangedListener);

    // Initial undo/redo state
    this.updateUndoRedoState(diagram);
  }

  private updateUndoRedoState(diagram: go.Diagram): void {
    this.canUndo.set(diagram.commandHandler.canUndo());
    this.canRedo.set(diagram.commandHandler.canRedo());
  }

  handlePanClick(): void {
    if (!this.diagram) return;
    this.setPanMode(this.diagram);
    this.toolMode.set('pan');
  }

  handleSelectClick(): void {
    if (!this.diagram) return;
    this.setSelectMode(this.diagram);
    this.toolMode.set('select');
  }

  handleUndo(): void {
    if (!this.diagram || !this.canUndo()) return;
    this.diagram.commandHandler.undo();
  }

  handleRedo(): void {
    if (!this.diagram || !this.canRedo()) return;
    this.diagram.commandHandler.redo();
  }

  private setPanMode(diagram: go.Diagram): void {
    diagram.commit((d) => {
      d.toolManager.panningTool.isEnabled = true;
      d.toolManager.dragSelectingTool.isEnabled = false;
      d.toolManager.draggingTool.isEnabled = false;
      d.defaultCursor = 'grab';
    }, 'tool-pan');

    const div = diagram.div as HTMLDivElement;
    div.style.cursor = 'grab';
  }

  private setSelectMode(diagram: go.Diagram): void {
    diagram.commit((d) => {
      d.toolManager.panningTool.isEnabled = false;
      d.toolManager.dragSelectingTool.isEnabled = true;
      d.toolManager.draggingTool.isEnabled = true;
      d.defaultCursor = 'default';
    }, 'tool-select');

    const div = diagram.div as HTMLDivElement;
    div.style.cursor = 'default';
  }
}

// apps/viz-scope-link/src/components/FloatingDock.tsx
import { useEffect, useState } from "react";
import { Hand, MousePointer2, Undo, Redo } from "lucide-react";
import * as go from "gojs";

interface FloatingDockProps {
  diagram: go.Diagram | null;
}

type ToolMode = "pan" | "select";

export function FloatingDock({ diagram }: FloatingDockProps) {
  const [toolMode, setToolMode] = useState<ToolMode>("pan");
  const [canUndo, setCanUndo] = useState(false);
  const [canRedo, setCanRedo] = useState(false);

  // Set pan mode as default when diagram is ready
  useEffect(() => {
    if (!diagram) return;
    
    // One-time initialization: enable infinite scroll
    diagram.commit(d => {
      d.allowHorizontalScroll = true;
      d.allowVerticalScroll = true;
      d.scrollMode = go.Diagram.InfiniteScroll;
    }, 'init-scroll');
    
    // Set pan mode as default
    diagram.commit(d => {
      d.toolManager.panningTool.isEnabled = true;
      d.toolManager.dragSelectingTool.isEnabled = false;
      d.toolManager.draggingTool.isEnabled = false;
      d.defaultCursor = 'grab';
    }, 'tool-pan');
    
    // Update cursor during panning
    const panTool = diagram.toolManager.panningTool;
    const originalDoMouseDown = panTool.doMouseDown;
    const originalDoMouseUp = panTool.doMouseUp;
    
    panTool.doMouseDown = function() {
      if (diagram.defaultCursor === 'grab') {
        diagram.div.style.cursor = "grabbing";
      }
      originalDoMouseDown.call(this);
    };
    
    panTool.doMouseUp = function() {
      if (diagram.defaultCursor === 'grab') {
        diagram.div.style.cursor = "grab";
      }
      originalDoMouseUp.call(this);
    };
  }, [diagram]);

  useEffect(() => {
    if (!diagram) return;

    const updateUndoRedoState = () => {
      setCanUndo(diagram.commandHandler.canUndo());
      setCanRedo(diagram.commandHandler.canRedo());
    };

    // Listen to model changes to update undo/redo state
    const listener = () => updateUndoRedoState();
    diagram.addModelChangedListener(listener);
    
    // Initial state
    updateUndoRedoState();

    return () => {
      diagram.removeModelChangedListener(listener);
    };
  }, [diagram]);

  const handlePanClick = () => {
    if (!diagram) return;
    
    diagram.commit(d => {
      d.toolManager.panningTool.isEnabled = true;
      d.toolManager.dragSelectingTool.isEnabled = false;
      d.toolManager.draggingTool.isEnabled = false;
      d.defaultCursor = 'grab';
    }, 'tool-pan');
    
    diagram.div.style.cursor = "grab";
    setToolMode("pan");
  };

  const handleSelectClick = () => {
    if (!diagram) return;
    
    diagram.commit(d => {
      d.toolManager.panningTool.isEnabled = false;
      d.toolManager.dragSelectingTool.isEnabled = true;
      d.toolManager.draggingTool.isEnabled = true;
      d.defaultCursor = 'default';
    }, 'tool-select');
    
    diagram.div.style.cursor = "default";
    setToolMode("select");
  };

  const handleUndo = () => {
    if (!diagram || !canUndo) return;
    diagram.commandHandler.undo();
  };

  const handleRedo = () => {
    if (!diagram || !canRedo) return;
    diagram.commandHandler.redo();
  };

  return (
    <div 
      className="absolute bottom-4 left-1/2 -translate-x-1/2 z-50 flex items-center gap-1.5 h-11 px-2 rounded-full bg-card border border-border shadow-lg backdrop-blur-sm"
      style={{
        boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 10px 15px -3px rgba(0, 0, 0, 0.1)'
      }}
    >
      {/* Pan button */}
      <button
        onClick={handlePanClick}
        disabled={!diagram}
        className={`
          w-9 h-9 rounded-full flex items-center justify-center
          transition-colors duration-150
          ${toolMode === "pan" 
            ? "bg-muted text-foreground" 
            : "text-muted-foreground hover:bg-muted/50"
          }
          ${!diagram ? "opacity-40 cursor-not-allowed" : ""}
        `}
        title="Pan (Hand tool)"
        aria-label="Pan tool"
      >
        <Hand size={18} strokeWidth={2} />
      </button>

      {/* Select button */}
      <button
        onClick={handleSelectClick}
        disabled={!diagram}
        className={`
          w-9 h-9 rounded-full flex items-center justify-center
          transition-colors duration-150
          ${toolMode === "select" 
            ? "bg-muted text-foreground" 
            : "text-muted-foreground hover:bg-muted/50"
          }
          ${!diagram ? "opacity-40 cursor-not-allowed" : ""}
        `}
        title="Select"
        aria-label="Select tool"
      >
        <MousePointer2 size={18} strokeWidth={2} />
      </button>

      {/* Separator */}
      <div className="w-px h-5 bg-border mx-0.5" />

      {/* Undo button */}
      <button
        onClick={handleUndo}
        disabled={!canUndo}
        className={`
          w-9 h-9 rounded-full flex items-center justify-center
          transition-colors duration-150
          ${canUndo
            ? "text-muted-foreground hover:bg-muted/50 cursor-pointer"
            : "text-muted-foreground/40 cursor-not-allowed"
          }
        `}
        title="Undo"
        aria-label="Undo"
      >
        <Undo size={18} strokeWidth={2} />
      </button>

      {/* Redo button */}
      <button
        onClick={handleRedo}
        disabled={!canRedo}
        className={`
          w-9 h-9 rounded-full flex items-center justify-center
          transition-colors duration-150
          ${canRedo
            ? "text-muted-foreground hover:bg-muted/50 cursor-pointer"
            : "text-muted-foreground/40 cursor-not-allowed"
          }
        `}
        title="Redo"
        aria-label="Redo"
      >
        <Redo size={18} strokeWidth={2} />
      </button>
    </div>
  );
}
