// apps/viz-scope-angular/src/app/features/runtime/components/immersive-toggle.component.ts
/**
 * Immersive Toggle Component
 * Toggle switch for immersive/fullscreen mode
 */

import { Component, Input, Output, EventEmitter } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatSlideToggleModule } from '@angular/material/slide-toggle';
import { MatIconModule } from '@angular/material/icon';
import { MatTooltipModule } from '@angular/material/tooltip';

@Component({
  selector: 'app-immersive-toggle',
  standalone: true,
  imports: [
    CommonModule,
    MatSlideToggleModule,
    MatIconModule,
    MatTooltipModule,
  ],
  template: `
    <div class="flex items-center gap-2 px-4 py-2 border-l border-gray-300 dark:border-gray-700">
      <div class="relative">
        <mat-icon class="text-gray-600 dark:text-gray-400">layers</mat-icon>
        @if (immersiveMode) {
        <span
          class="absolute -top-1 -right-1 flex h-2 w-2"
          aria-label="Immersive mode active"
        >
          <span
            class="animate-ping absolute inline-flex h-full w-full rounded-full bg-blue-500 opacity-75"
          ></span>
          <span
            class="relative inline-flex rounded-full h-2 w-2 bg-blue-500"
          ></span>
        </span>
        }
      </div>

      <mat-slide-toggle
        [checked]="immersiveMode"
        (change)="toggle.emit($event.checked)"
        [disabled]="true"
        color="primary"
      >
        <span class="text-sm font-medium">Immersive</span>
      </mat-slide-toggle>

      <mat-icon
        class="text-gray-600 dark:text-gray-400 cursor-help"
        matTooltip="Toggle Immersive Mode (I) - View multiple topologies simultaneously"
        matTooltipPosition="below"
      >
        info
      </mat-icon>
    </div>
  `,
  styles: [
    `
      :host {
        display: contents;
      }

      @keyframes ping {
        75%,
        100% {
          transform: scale(2);
          opacity: 0;
        }
      }

      .animate-ping {
        animation: ping 1s cubic-bezier(0, 0, 0.2, 1) infinite;
      }
    `,
  ],
})
export class ImmersiveToggleComponent {
  @Input() immersiveMode = false;
  @Output() toggle = new EventEmitter<boolean>();
}

// apps/viz-scope-link/src/components/ImmersiveToggle.tsx
import { Switch } from "@/components/ui/switch";
import { Label } from "@/components/ui/label";
import { Layers, Info } from "lucide-react";
import { Tooltip, TooltipContent, TooltipProvider, TooltipTrigger } from "@/components/ui/tooltip";

interface ImmersiveToggleProps {
  immersiveMode: boolean;
  onToggle: (value: boolean) => void;
}

export function ImmersiveToggle({ immersiveMode, onToggle }: ImmersiveToggleProps) {
  return (
    <div className="flex items-center gap-2 px-4 py-2 border-l border-border">
      <div className="relative">
        <Layers className="h-4 w-4 text-muted-foreground" />
        {immersiveMode && (
          <span
            className="absolute -top-1 -right-1 flex h-2 w-2"
            aria-label="Immersive mode active"
          >
            <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-primary opacity-75" />
            <span className="relative inline-flex rounded-full h-2 w-2 bg-primary" />
          </span>
        )}
      </div>
      <Switch id="immersive-mode" checked={immersiveMode} onCheckedChange={onToggle} disabled />
      <Label htmlFor="immersive-mode" className="text-sm font-medium">
        Immersive
      </Label>
      <TooltipProvider>
        <Tooltip>
          <TooltipTrigger asChild>
            <Info className="h-4 w-4 text-muted-foreground cursor-help" />
          </TooltipTrigger>
          <TooltipContent>
            <p>Toggle Immersive Mode (I) - View multiple topologies simultaneously</p>
          </TooltipContent>
        </Tooltip>
      </TooltipProvider>
    </div>
  );
}
