// apps/viz-scope-angular/src/app/features/runtime/dialogs/partial-fold-dialog.component.ts
/**
 * Partial Fold Dialog Component
 * Modal dialog for selecting specific nodes to fold into a meta-node
 */

import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import {
  MAT_DIALOG_DATA,
  MatDialogModule,
  MatDialogRef,
} from '@angular/material/dialog';
import { MatButtonModule } from '@angular/material/button';
import { MatCheckboxModule } from '@angular/material/checkbox';
import { NodeType, Node } from '../../../models';

export interface PartialFoldDialogData {
  nodeType: NodeType;
  nodes: Node[];
  getNodeName: (nodeId: string) => string;
}

export interface PartialFoldDialogResult {
  nodeIds: string[];
  foldAll: boolean;
}

@Component({
  selector: 'app-partial-fold-dialog',
  standalone: true,
  imports: [CommonModule, MatDialogModule, MatButtonModule, MatCheckboxModule],
  template: `
    <h2 mat-dialog-title class="flex items-center gap-2">
      <!-- Icon placeholder -->
      <span class="w-5 h-5 rounded bg-blue-500"></span>
      <span>Partial Fold: {{ data.nodeType }}</span>
    </h2>

    <mat-dialog-content>
      <p class="text-sm text-gray-600 dark:text-gray-400 mb-4">
        Select which {{ data.nodeType }} nodes to fold into a meta-node.
      </p>

      <div class="max-h-[400px] overflow-y-auto space-y-2">
        @for (node of data.nodes; track node.id) {
        <div
          role="button"
          tabindex="0"
          class="flex items-center gap-3 p-2 rounded-md border border-gray-300 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-800 cursor-pointer transition-colors"
          (click)="toggleNode(node.id)"
          (keyup.enter)="toggleNode(node.id)"
          (keyup.space)="toggleNode(node.id)"
        >
          <mat-checkbox
            [checked]="selectedNodeIds.has(node.id)"
            (change)="toggleNode(node.id)"
            (click)="$event.stopPropagation()"
          />
          <div class="flex-1 min-w-0">
            <div
              class="text-sm font-medium text-gray-900 dark:text-white truncate"
            >
              {{ data.getNodeName(node.id) }}
            </div>
            <div class="text-xs text-gray-600 dark:text-gray-400">
              {{ node.id }}
            </div>
          </div>
        </div>
        }
      </div>
    </mat-dialog-content>

    <mat-dialog-actions align="end">
      <button mat-button (click)="onCancel()">Cancel</button>
      <button mat-stroked-button (click)="onFoldAll()">Fold All</button>
      <button
        mat-raised-button
        color="primary"
        (click)="onFoldSelected()"
        [disabled]="selectedNodeIds.size === 0"
      >
        Fold Selected ({{ selectedNodeIds.size }})
      </button>
    </mat-dialog-actions>
  `,
  styles: [
    `
      :host {
        display: block;
      }

      mat-dialog-content {
        min-width: 400px;
        max-width: 500px;
      }
    `,
  ],
})
export class PartialFoldDialogComponent {
  readonly dialogRef = inject(MatDialogRef<PartialFoldDialogComponent>);
  readonly data = inject<PartialFoldDialogData>(MAT_DIALOG_DATA);

  selectedNodeIds = new Set<string>();

  toggleNode(nodeId: string): void {
    if (this.selectedNodeIds.has(nodeId)) {
      this.selectedNodeIds.delete(nodeId);
    } else {
      this.selectedNodeIds.add(nodeId);
    }
    // Trigger change detection
    this.selectedNodeIds = new Set(this.selectedNodeIds);
  }

  onFoldSelected(): void {
    if (this.selectedNodeIds.size > 0) {
      const result: PartialFoldDialogResult = {
        nodeIds: Array.from(this.selectedNodeIds),
        foldAll: false,
      };
      this.dialogRef.close(result);
    }
  }

  onFoldAll(): void {
    const result: PartialFoldDialogResult = {
      nodeIds: this.data.nodes.map((n: Node) => n.id),
      foldAll: true,
    };
    this.dialogRef.close(result);
  }

  onCancel(): void {
    this.dialogRef.close();
  }
}

// apps/viz-scope-link/src/components/PartialFoldDialog.tsx
import { useState } from "react";
import { NodeType, Node as GraphNode } from "@/lib/models";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { ScrollArea } from "@/components/ui/scroll-area";
import { NodeTypeIcon } from "@/components/icons/NodeTypeIcon";

interface PartialFoldDialogProps {
  open: boolean;
  onClose: () => void;
  nodeType: NodeType;
  nodes: GraphNode[];
  onFold: (nodeIds: string[]) => void;
  getNodeName: (nodeId: string) => string;
}

export function PartialFoldDialog({
  open,
  onClose,
  nodeType,
  nodes,
  onFold,
  getNodeName,
}: PartialFoldDialogProps) {
  const [selectedNodeIds, setSelectedNodeIds] = useState<Set<string>>(new Set());

  const handleToggle = (nodeId: string) => {
    setSelectedNodeIds((prev) => {
      const newSet = new Set(prev);
      if (newSet.has(nodeId)) {
        newSet.delete(nodeId);
      } else {
        newSet.add(nodeId);
      }
      return newSet;
    });
  };

  const handleFoldSelected = () => {
    if (selectedNodeIds.size > 0) {
      onFold(Array.from(selectedNodeIds));
      onClose();
      setSelectedNodeIds(new Set());
    }
  };

  const handleFoldAll = () => {
    onFold(nodes.map((n) => n.id));
    onClose();
    setSelectedNodeIds(new Set());
  };

  return (
    <Dialog open={open} onOpenChange={(open) => !open && onClose()}>
      <DialogContent className="sm:max-w-[500px]">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <NodeTypeIcon type={nodeType} size={20} className="text-primary" />
            Partial Fold: {nodeType}
          </DialogTitle>
          <DialogDescription>
            Select which {nodeType} nodes to fold into a meta-node.
          </DialogDescription>
        </DialogHeader>

        <ScrollArea className="max-h-[400px] pr-4">
          <div className="space-y-2">
            {nodes.map((node) => (
              <div
                key={node.id}
                className="flex items-center gap-3 p-2 rounded-md border border-border hover:bg-muted/50 cursor-pointer"
                onClick={() => handleToggle(node.id)}
              >
                <Checkbox
                  checked={selectedNodeIds.has(node.id)}
                  onCheckedChange={() => handleToggle(node.id)}
                />
                <div className="flex-1 min-w-0">
                  <div className="text-sm font-medium truncate">{getNodeName(node.id)}</div>
                  <div className="text-xs text-muted-foreground">{node.id}</div>
                </div>
              </div>
            ))}
          </div>
        </ScrollArea>

        <DialogFooter>
          <Button variant="outline" onClick={onClose}>
            Cancel
          </Button>
          <Button variant="outline" onClick={handleFoldAll}>
            Fold All
          </Button>
          <Button onClick={handleFoldSelected} disabled={selectedNodeIds.size === 0}>
            Fold Selected ({selectedNodeIds.size})
          </Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
