// apps/viz-scope-link/src/components/BranchDataPanel.tsx
import { X } from "lucide-react";
import { Node, NodeType, Variable, TimeWindow } from "@/lib/models";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Badge } from "@/components/ui/badge";
import { NodeTypeIcon } from "@/components/icons/NodeTypeIcon";
import { getBranchNodes } from "@/lib/scope";
import { electricalTopology } from "@/mocks/topologies";
import { getAlignedTimePeriod } from "@/lib/timeWindows";

interface BranchDataPanelProps {
  rootNode: Node;
  onClose: () => void;
  overlayMetric: Variable | null;
  timeWindow: TimeWindow;
}

export function BranchDataPanel({
  rootNode,
  onClose,
  overlayMetric,
  timeWindow,
}: BranchDataPanelProps) {
  // Get all branch nodes (MANTO-only)
  const branchNodeIds = getBranchNodes(rootNode.id, electricalTopology);
  const branchNodes = Array.from(branchNodeIds)
    .map((id) => electricalTopology.nodes.get(id))
    .filter((n): n is Node => n !== undefined);

  // Count node types
  const typeCounts = new Map<NodeType, number>();
  for (const node of branchNodes) {
    typeCounts.set(node.type, (typeCounts.get(node.type) || 0) + 1);
  }

  // Consolidate integrated metrics only
  const integratedMetrics = branchNodes
    .flatMap((n) => n.metrics)
    .filter((m) => m.variable.isIntegrated);

  const metricsByVariable = new Map<string, typeof integratedMetrics>();
  for (const metric of integratedMetrics) {
    const key = metric.variable.id;
    if (!metricsByVariable.has(key)) {
      metricsByVariable.set(key, []);
    }
    metricsByVariable.get(key)!.push(metric);
  }

  const consolidatedMetrics = Array.from(metricsByVariable.entries()).map(
    ([varId, metrics]) => {
      const variable = metrics[0].variable;
      let consolidatedValue: number;

      if (variable.type === "extensive") {
        consolidatedValue = metrics.reduce((sum, m) => sum + m.value, 0);
      } else {
        consolidatedValue =
          metrics.reduce((sum, m) => sum + m.value, 0) / metrics.length;
      }

      return {
        variable,
        value: consolidatedValue,
      };
    }
  );

  // Time alignment
  const timePeriod = overlayMetric
    ? getAlignedTimePeriod(timeWindow, overlayMetric.sit, timeWindow)
    : { period: timeWindow, shouldConsolidate: false };

  return (
    <div className="w-96 border-l border-border bg-card flex flex-col h-full animate-slide-in-right">
      <div className="p-4 border-b border-border flex items-start justify-between">
        <div className="flex-1">
          <h3 className="text-lg font-semibold mb-1">Branch Data</h3>
          <p className="text-sm text-muted-foreground">
            Root: {rootNode.name}
          </p>
          <Badge variant="secondary" className="mt-2">
            {branchNodes.length} nodes
          </Badge>
        </div>
        <Button variant="ghost" size="sm" onClick={onClose} className="h-8 w-8 p-0">
          <X className="h-4 w-4" />
        </Button>
      </div>

      <div className="p-4 border-b border-border bg-muted">
        <p className="text-xs text-muted-foreground">Time Period (MANTO only) • {timePeriod.period}</p>
        {timePeriod.shouldConsolidate && (
          <p className="text-xs text-warning mt-1">Data consolidated to window</p>
        )}
      </div>

      <ScrollArea className="flex-1">
        <div className="p-4 space-y-4">
          <div>
            <h4 className="text-sm font-semibold mb-2">
              Consolidated Metrics (Integrated Only)
            </h4>
            <div className="space-y-2">
              {consolidatedMetrics.length > 0 ? (
                consolidatedMetrics.map(({ variable, value }) => (
                  <div
                    key={variable.id}
                    className="flex items-center justify-between p-3 rounded-md bg-secondary"
                  >
                    <div>
                      <p className="text-sm font-medium">{variable.name}</p>
                      <p className="text-xs text-muted-foreground">
                        {variable.type === "extensive" ? "Sum" : "Average"}
                      </p>
                    </div>
                    <div className="text-right">
                      <p className="text-lg font-semibold">{value.toFixed(2)}</p>
                      <p className="text-xs text-muted-foreground">
                        {variable.unit}
                      </p>
                    </div>
                  </div>
                ))
              ) : (
                <p className="text-sm text-muted-foreground">
                  No integrated metrics available
                </p>
              )}
            </div>
          </div>

          <div>
            <h4 className="text-sm font-semibold mb-2">Branch Inventory</h4>
            <div className="space-y-2">
              {Array.from(typeCounts.entries())
                .sort((a, b) => a[0].localeCompare(b[0]))
                .map(([type, count]) => (
                  <div
                    key={type}
                    className="flex items-center justify-between p-3 rounded-md bg-secondary"
                  >
                    <div className="flex items-center gap-2">
                      <NodeTypeIcon type={type} className="text-primary" size={16} />
                      <p className="text-sm font-medium">{type}</p>
                    </div>
                    <Badge variant="outline">{count}</Badge>
                  </div>
                ))}
              <div className="flex items-center justify-between p-3 rounded-md bg-primary/10 border border-primary">
                <p className="text-sm font-semibold">Total Nodes</p>
                <Badge variant="default">{branchNodes.length}</Badge>
              </div>
            </div>
          </div>
        </div>
      </ScrollArea>
    </div>
  );
}

// apps/viz-scope-angular/src/app/features/runtime/components/branch-data-panel.component.ts
/**
 * Branch Data Panel Component
 * Shows consolidated data for a branch (hidden subtree)
 */

import {
  Component,
  Input,
  Output,
  EventEmitter,
  computed,
  inject,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { RuntimeStateService } from '../../../core/services/runtime-state.service';
import { Node, NodeType } from '../../../models';
import { ScopeService } from '../../../core/services';

interface ConsolidatedMetric {
  id: string;
  name: string;
  type: string;
  unit: string;
  value: number;
  aggregationType: 'Sum' | 'Average';
}

@Component({
  selector: 'app-branch-data-panel',
  standalone: true,
  imports: [CommonModule],
  template: `
    @if (branchRootNode()) { @let rootNode = branchRootNode(); @let branchData =
    getBranchData(rootNode!);

    <div
      class="w-96 border-l border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900 flex flex-col h-full"
    >
      <!-- Header -->
      <div
        class="p-4 border-b border-gray-200 dark:border-gray-800 flex items-start justify-between"
      >
        <div class="flex-1">
          <h3 class="text-lg font-semibold text-gray-900 dark:text-white mb-1">
            Branch Data
          </h3>
          <p class="text-sm text-gray-600 dark:text-gray-400">
            Root: {{ rootNode!.name }}
          </p>
          <span
            class="inline-flex items-center px-2 py-0.5 mt-2 text-xs font-medium bg-gray-100 dark:bg-gray-800 text-gray-800 dark:text-gray-200 rounded"
          >
            {{ branchData.totalNodes }} nodes
          </span>
        </div>
        <button
          type="button"
          (click)="close()"
          class="h-8 w-8 flex items-center justify-center text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200 transition-colors rounded"
        >
          <span class="text-xl">✕</span>
        </button>
      </div>

      <!-- Time Period Info -->
      <div
        class="p-4 border-b border-gray-200 dark:border-gray-800 bg-gray-50 dark:bg-gray-800/50"
      >
        <p class="text-xs text-gray-600 dark:text-gray-400">
          Time Period (MANTO only) • {{ timeWindow() }}
        </p>
      </div>

      <!-- Content -->
      <div class="flex-1 overflow-y-auto">
        <div class="p-4 space-y-4">
          <!-- Consolidated Metrics -->
          <div>
            <h4
              class="text-sm font-semibold text-gray-900 dark:text-white mb-2"
            >
              Consolidated Metrics (Integrated Only)
            </h4>
            <div class="space-y-2">
              @if (branchData.consolidatedMetrics.length > 0) { @for (metric of
              branchData.consolidatedMetrics; track metric.id) {
              <div
                class="flex items-center justify-between p-3 rounded-md bg-gray-100 dark:bg-gray-800"
              >
                <div>
                  <p class="text-sm font-medium text-gray-900 dark:text-white">
                    {{ metric.name }}
                  </p>
                  <p class="text-xs text-gray-600 dark:text-gray-400">
                    {{ metric.aggregationType }}
                  </p>
                </div>
                <div class="text-right">
                  <p
                    class="text-lg font-semibold text-gray-900 dark:text-white"
                  >
                    {{ metric.value.toFixed(2) }}
                  </p>
                  <p class="text-xs text-gray-600 dark:text-gray-400">
                    {{ metric.unit }}
                  </p>
                </div>
              </div>
              } } @else {
              <p class="text-sm text-gray-600 dark:text-gray-400">
                No integrated metrics available
              </p>
              }
            </div>
          </div>

          <!-- Branch Inventory -->
          <div>
            <h4
              class="text-sm font-semibold text-gray-900 dark:text-white mb-2"
            >
              Branch Inventory
            </h4>
            <div class="space-y-2">
              @for (typeCount of branchData.typeCounts; track typeCount.type) {
              <div
                class="flex items-center justify-between p-3 rounded-md bg-gray-100 dark:bg-gray-800"
              >
                <div class="flex items-center gap-2">
                  <!-- Icon placeholder -->
                  <span class="w-4 h-4 rounded bg-blue-500"></span>
                  <p class="text-sm font-medium text-gray-900 dark:text-white">
                    {{ typeCount.type }}
                  </p>
                </div>
                <span
                  class="inline-flex items-center px-2 py-0.5 text-xs font-medium border border-gray-300 dark:border-gray-700 text-gray-800 dark:text-gray-200 rounded"
                >
                  {{ typeCount.count }}
                </span>
              </div>
              }

              <!-- Total -->
              <div
                class="flex items-center justify-between p-3 rounded-md bg-blue-50 dark:bg-blue-900/20 border border-blue-300 dark:border-blue-700"
              >
                <p class="text-sm font-semibold text-gray-900 dark:text-white">
                  Total Nodes
                </p>
                <span
                  class="inline-flex items-center px-2 py-0.5 text-xs font-medium bg-blue-500 text-white rounded"
                >
                  {{ branchData.totalNodes }}
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    }
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
})
export class BranchDataPanelComponent {
  @Input() branchRootId: string | null = null;
  @Output() panelClose = new EventEmitter<void>();

  private readonly runtimeState = inject(RuntimeStateService);
  private readonly scopeService = inject(ScopeService);

  readonly timeWindow = this.runtimeState.timeWindow;
  readonly branchRootNode = computed(() => {
    if (!this.branchRootId) return null;

    const topology = this.runtimeState.topology();
    return (topology?.nodes.get(this.branchRootId) as Node | undefined) || null;
  });

  close(): void {
    this.panelClose.emit();
  }

  getBranchData(rootNode: Node): {
    totalNodes: number;
    consolidatedMetrics: ConsolidatedMetric[];
    typeCounts: Array<{ type: NodeType; count: number }>;
  } {
    const topology = this.runtimeState.topology();
    if (!topology) {
      return { totalNodes: 0, consolidatedMetrics: [], typeCounts: [] };
    }

    // Get all branch nodes using scopeService
    const branchNodeIds = this.scopeService.getBranchNodes(
      rootNode.id,
      topology
    );
    const branchNodes: Node[] = [];

    for (const nodeId of branchNodeIds) {
      const node = topology.nodes.get(nodeId) as Node | undefined;
      if (node) {
        branchNodes.push(node);
      }
    }

    // Count node types
    const typeCounts = new Map<NodeType, number>();
    for (const node of branchNodes) {
      typeCounts.set(node.type, (typeCounts.get(node.type) || 0) + 1);
    }

    // Consolidate integrated metrics only
    const integratedMetrics = branchNodes
      .flatMap((n) => n.metrics)
      .filter((m) => m.variable.isIntegrated);

    const metricsByVariable = new Map<string, typeof integratedMetrics>();
    for (const metric of integratedMetrics) {
      const key = metric.variable.id;
      if (!metricsByVariable.has(key)) {
        metricsByVariable.set(key, []);
      }
      const metricsArray = metricsByVariable.get(key);
      if (metricsArray) {
        metricsArray.push(metric);
      }
    }

    const consolidatedMetrics: ConsolidatedMetric[] = Array.from(
      metricsByVariable.entries()
    ).map(([, metrics]) => {
      const variable = metrics[0].variable;
      let consolidatedValue: number;
      let aggregationType: 'Sum' | 'Average';

      if (variable.type === 'extensive') {
        consolidatedValue = metrics.reduce((sum, m) => sum + m.value, 0);
        aggregationType = 'Sum';
      } else {
        consolidatedValue =
          metrics.reduce((sum, m) => sum + m.value, 0) / metrics.length;
        aggregationType = 'Average';
      }

      return {
        id: variable.id,
        name: variable.name,
        type: variable.type,
        unit: variable.unit,
        value: consolidatedValue,
        aggregationType,
      };
    });

    return {
      totalNodes: branchNodes.length,
      consolidatedMetrics,
      typeCounts: Array.from(typeCounts.entries())
        .map(([type, count]) => ({ type, count }))
        .sort((a, b) => a.type.localeCompare(b.type)),
    };
  }
}
