// apps/viz-scope-link/src/components/MetricSelector.tsx
import { Variable, TimeWindow } from "@/lib/models";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { availableVariables } from "@/mocks/topologies";
import { getAllowedWindows } from "@/lib/timeWindows";

interface MetricSelectorProps {
  selectedMetric: Variable | null;
  onMetricChange: (metric: Variable | null) => void;
  selectedWindow: TimeWindow;
  onWindowChange: (window: TimeWindow) => void;
}

export function MetricSelector({
  selectedMetric,
  onMetricChange,
  selectedWindow,
  onWindowChange,
}: MetricSelectorProps) {
  const allowedWindows = selectedMetric
    ? getAllowedWindows(selectedMetric)
    : ["Latest", "15m", "1h", "3h", "12h", "24h", "3d", "7d", "14d", "30d", "Custom"];

  return (
    <div className="flex items-center gap-4 p-4 border-b border-border bg-card">
      <div className="flex items-center gap-2">
        <label className="text-sm font-medium whitespace-nowrap">
          Overlay Metric:
        </label>
        <Select
          value={selectedMetric?.id || "none"}
          onValueChange={(value) => {
            if (value === "none") {
              onMetricChange(null as any);
            } else {
              const metric = availableVariables.find((v) => v.id === value);
              if (metric) onMetricChange(metric);
            }
          }}
        >
          <SelectTrigger className="w-[180px]">
            <SelectValue placeholder="Select metric" />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="none">None</SelectItem>
            {availableVariables.map((variable) => (
              <SelectItem key={variable.id} value={variable.id}>
                {variable.name} ({variable.unit})
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>

      <div className="flex items-center gap-2">
        <label className="text-sm font-medium whitespace-nowrap">
          Time Window:
        </label>
        <Select value={selectedWindow} onValueChange={(value) => onWindowChange(value as TimeWindow)}>
          <SelectTrigger className="w-[140px]">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            {(allowedWindows as TimeWindow[]).map((window) => (
              <SelectItem key={window} value={window}>
                {window}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>
      </div>
    </div>
  );
}

// apps/viz-scope-angular/src/app/features/runtime/components/metric-selector.component.ts
/**
 * Metric Selector Component
 * Dropdown selectors for overlay metric and time window
 */

import { Component, Input, Output, EventEmitter, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatSelectModule } from '@angular/material/select';
import { MatFormFieldModule } from '@angular/material/form-field';
import { Variable, TimeWindow } from '../../../models';
import { getAllowedWindows } from '../../../core/services/time-window.service';

@Component({
  selector: 'app-metric-selector',
  standalone: true,
  imports: [CommonModule, MatSelectModule, MatFormFieldModule],
  template: `
    <div
      class="flex items-center gap-4 p-4 border-b border-gray-300 dark:border-gray-700 bg-white dark:bg-gray-900"
    >
      <!-- Metric Selector -->
      <div class="flex items-center gap-2">
        <label class="text-sm font-medium whitespace-nowrap">
          Overlay Metric:
        </label>
        <mat-form-field appearance="outline" class="metric-select">
          <mat-select
            [value]="selectedMetric?.id || 'none'"
            (selectionChange)="onMetricChange($event.value)"
          >
            <mat-option value="none">None</mat-option>
            @for (variable of availableVariables; track variable.id) {
            <mat-option [value]="variable.id">
              {{ variable.name }} ({{ variable.unit }})
            </mat-option>
            }
          </mat-select>
        </mat-form-field>
      </div>

      <!-- Time Window Selector -->
      <div class="flex items-center gap-2">
        <label class="text-sm font-medium whitespace-nowrap">
          Time Window:
        </label>
        <mat-form-field appearance="outline" class="window-select">
          <mat-select
            [value]="selectedWindow"
            (selectionChange)="windowChange.emit($event.value)"
          >
            @for (window of allowedWindows(); track window) {
            <mat-option [value]="window">{{ window }}</mat-option>
            }
          </mat-select>
        </mat-form-field>
      </div>
    </div>
  `,
  styles: [
    `
      :host {
        display: contents;
      }

      ::ng-deep {
        .metric-select .mat-mdc-form-field-infix {
          width: 180px;
        }

        .window-select .mat-mdc-form-field-infix {
          width: 140px;
        }

        .metric-select,
        .window-select {
          .mat-mdc-text-field-wrapper {
            padding: 0;
          }

          .mat-mdc-form-field-subscript-wrapper {
            display: none;
          }
        }
      }
    `,
  ],
})
export class MetricSelectorComponent {
  @Input() selectedMetric: Variable | null = null;
  @Input() selectedWindow: TimeWindow = 'Latest';
  @Input() availableVariables: Variable[] = [];

  @Output() metricChange = new EventEmitter<Variable | null>();
  @Output() windowChange = new EventEmitter<TimeWindow>();

  // Computed allowed windows based on selected metric
  readonly allowedWindows = computed<TimeWindow[]>(() => {
    if (this.selectedMetric) {
      return getAllowedWindows(this.selectedMetric);
    }
    return [
      'Latest',
      '15m',
      '1h',
      '3h',
      '12h',
      '24h',
      '3d',
      '7d',
      '14d',
      '30d',
      'Custom',
    ] as TimeWindow[];
  });

  onMetricChange(metricId: string): void {
    if (metricId === 'none') {
      this.metricChange.emit(null);
    } else {
      const metric = this.availableVariables.find((v) => v.id === metricId);
      if (metric) {
        this.metricChange.emit(metric);
      }
    }
  }
}
