// apps/viz-scope-link/src/components/NodeDataPanel.tsx
import { X, AlertCircle } from "lucide-react";
import { Node, Variable, TimeWindow } from "@/lib/models";
import { Button } from "@/components/ui/button";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Badge } from "@/components/ui/badge";
import { NodeTypeIcon } from "@/components/icons/NodeTypeIcon";
import { getAlignedTimePeriod } from "@/lib/timeWindows";
import { electricalTopology, coolingTopology } from "@/mocks/topologies";

interface NodeDataPanelProps {
  node: Node;
  onClose: () => void;
  overlayMetric: Variable | null;
  timeWindow: TimeWindow;
}

// Metric families for organizing metrics
const METRIC_FAMILIES = {
  emissions: { name: "Emissions", order: 1 },
  energy: { name: "Energy & Power", order: 2 },
  environmental: { name: "Environmental", order: 3 },
  other: { name: "Other Metrics", order: 4 },
};

function getMetricFamily(variableName: string): keyof typeof METRIC_FAMILIES {
  const name = variableName.toLowerCase();
  if (name.includes("co2") || name.includes("emission")) return "emissions";
  if (name.includes("power") || name.includes("energy") || name.includes("current") || name.includes("voltage")) return "energy";
  if (name.includes("temperature") || name.includes("humidity")) return "environmental";
  return "other";
}

export function NodeDataPanel({
  node,
  onClose,
  overlayMetric,
  timeWindow,
}: NodeDataPanelProps) {
  // Get data across all topologies
  const allNodes: Node[] = [];
  if (node.topologies.includes("Electrical")) {
    const elecNode = electricalTopology.nodes.get(node.id);
    if (elecNode) allNodes.push(elecNode);
  }
  if (node.topologies.includes("Cooling")) {
    const coolNode = coolingTopology.nodes.get(node.id);
    if (coolNode) allNodes.push(coolNode);
  }

  // Merge metrics from all topologies
  const allMetrics = allNodes.flatMap((n) => n.metrics);
  const uniqueMetrics = Array.from(
    new Map(allMetrics.map((m) => [m.variable.id, m])).values()
  );

  // Group metrics by family
  const metricsByFamily = uniqueMetrics.reduce((acc, metric) => {
    const family = getMetricFamily(metric.variable.name);
    if (!acc[family]) acc[family] = [];
    acc[family].push(metric);
    return acc;
  }, {} as Record<keyof typeof METRIC_FAMILIES, typeof uniqueMetrics>);

  // Sort families by order
  const sortedFamilies = (Object.keys(metricsByFamily) as Array<keyof typeof METRIC_FAMILIES>)
    .sort((a, b) => METRIC_FAMILIES[a].order - METRIC_FAMILIES[b].order);

  // Time alignment
  const timePeriod = overlayMetric
    ? getAlignedTimePeriod(timeWindow, overlayMetric.sit, timeWindow)
    : { period: timeWindow, shouldConsolidate: false };

  return (
    <div className="w-96 border-l border-border bg-card flex flex-col h-full animate-slide-in-right">
      <div className="p-4 border-b border-border flex items-start justify-between">
        <div className="flex-1">
          <div className="flex items-center gap-2 mb-1">
            <NodeTypeIcon type={node.type} className="text-primary" size={16} />
            <h3 className="text-lg font-semibold">{node.name}</h3>
            {node.alerts && node.alerts.length > 0 && (
              <Badge variant="destructive" className="flex items-center gap-1">
                <AlertCircle className="h-3 w-3" />
                Alert
              </Badge>
            )}
          </div>
          <p className="text-sm text-muted-foreground">{node.type}</p>
          <div className="flex gap-1 mt-2">
            {node.topologies.map((topo) => (
              <Badge key={topo} variant="secondary" className="text-xs">
                {topo}
              </Badge>
            ))}
          </div>
        </div>
        <Button variant="ghost" size="sm" onClick={onClose} className="h-8 w-8 p-0">
          <X className="h-4 w-4" />
        </Button>
      </div>

      <div className="p-4 border-b border-border bg-muted">
        <p className="text-xs text-muted-foreground">Time Period • {timePeriod.period}</p>
        {timePeriod.shouldConsolidate && (
          <p className="text-xs text-warning mt-1">Data consolidated to window</p>
        )}
      </div>

      <ScrollArea className="flex-1">
        <div className="p-4 space-y-4">
          {node.alerts && node.alerts.length > 0 && (
            <div>
              <h4 className="text-sm font-semibold mb-2">Alerts</h4>
              <div className="space-y-2">
                {node.alerts.map((alert, idx) => (
                  <div
                    key={idx}
                    className="flex items-start gap-2 p-3 rounded-md bg-destructive/10 border border-destructive/20"
                  >
                    <AlertCircle className="h-4 w-4 text-destructive mt-0.5" />
                    <p className="text-sm">{alert}</p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {sortedFamilies.map((family) => (
            <div key={family}>
              <h4 className="text-sm font-semibold mb-2">{METRIC_FAMILIES[family].name}</h4>
              <div className="space-y-2">
                {metricsByFamily[family].map((metric) => (
                  <div
                    key={metric.variable.id}
                    className="p-3 rounded-md bg-secondary"
                  >
                    <div className="flex items-center justify-between">
                      <div>
                        <p className="text-sm font-medium">{metric.variable.name}</p>
                        <p className="text-xs text-muted-foreground">
                          {metric.variable.type} • SIT: {metric.variable.sit}m
                          {metric.variable.isIntegrated && " • Integrated"}
                        </p>
                      </div>
                      <div className="text-right">
                        <p className="text-lg font-semibold">
                          {metric.value.toFixed(2)}
                        </p>
                        <p className="text-xs text-muted-foreground">
                          {metric.variable.unit}
                        </p>
                      </div>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          ))}

          <div>
            <h4 className="text-sm font-semibold mb-2">Connections</h4>
            <div className="grid grid-cols-2 gap-2">
              <div className="p-3 rounded-md bg-secondary text-center">
                <p className="text-xs text-muted-foreground mb-1">Parents</p>
                <p className="text-2xl font-bold">{node.parents.length}</p>
              </div>
              <div className="p-3 rounded-md bg-secondary text-center">
                <p className="text-xs text-muted-foreground mb-1">Children</p>
                <p className="text-2xl font-bold">{node.children.length}</p>
              </div>
            </div>
          </div>
        </div>
      </ScrollArea>
    </div>
  );
}

// apps/viz-scope-angular/src/app/features/runtime/components/node-data-panel.component.ts
/**
 * Node Data Panel Component
 * Side panel showing detailed information about a selected node
 */

import {
  Component,
  Output,
  EventEmitter,
  computed,
  inject,
} from '@angular/core';
import { CommonModule } from '@angular/common';
import { RuntimeStateService } from '../../../core/services/runtime-state.service';
import { Node } from '../../../models';

// Metric families for organizing metrics
const METRIC_FAMILIES = {
  emissions: { name: 'Emissions', order: 1 },
  energy: { name: 'Energy & Power', order: 2 },
  environmental: { name: 'Environmental', order: 3 },
  other: { name: 'Other Metrics', order: 4 },
} as const;

type MetricFamily = keyof typeof METRIC_FAMILIES;

interface MetricDisplay {
  id: string;
  name: string;
  type: string;
  sit: number;
  unit: string;
  value: number;
  isIntegrated: boolean;
}

@Component({
  selector: 'app-node-data-panel',
  standalone: true,
  imports: [CommonModule],
  template: `
    @if (selectedNode()) { @let node = selectedNode();
    <div
      class="w-96 border-l border-gray-200 dark:border-gray-800 bg-white dark:bg-gray-900 flex flex-col h-full p-2"
    >
      <!-- Header -->
      <div
        class="p-4 border-b border-gray-200 dark:border-gray-800 flex items-start justify-between"
      >
        <div class="flex-1">
          <div class="flex items-center gap-2 mb-1">
            <!-- Icon placeholder -->
            <span class="w-4 h-4 rounded bg-blue-500"></span>
            <h3 class="text-lg font-semibold text-gray-900 dark:text-white">
              {{ node!.name }}
            </h3>
            @if (node!.alerts && node!.alerts.length > 0) {
            <span
              class="inline-flex items-center gap-1 px-2 py-0.5 text-xs font-medium bg-red-100 dark:bg-red-900 text-red-800 dark:text-red-200 rounded"
            >
              ⚠️ Alert
            </span>
            }
          </div>
          <p class="text-sm text-gray-600 dark:text-gray-400">
            {{ node!.type }}
          </p>
          <div class="flex gap-1 mt-2">
            @for (topo of node!.topologies; track topo) {
            <span
              class="inline-flex items-center px-2 py-0.5 text-xs font-medium bg-gray-100 dark:bg-gray-800 text-gray-800 dark:text-gray-200 rounded"
            >
              {{ topo }}
            </span>
            }
          </div>
        </div>
        <button
          type="button"
          (click)="close()"
          class="h-8 w-8 flex items-center justify-center text-gray-500 hover:text-gray-700 dark:text-gray-400 dark:hover:text-gray-200 transition-colors rounded"
        >
          <span class="text-xl">✕</span>
        </button>
      </div>

      <!-- Time Period Info -->
      <div
        class="p-4 border-b border-gray-200 dark:border-gray-800 bg-gray-50 dark:bg-gray-800/50"
      >
        <p class="text-xs text-gray-600 dark:text-gray-400">
          Time Period • {{ timeWindow() }}
        </p>
      </div>

      <!-- Content -->
      <div class="flex-1 overflow-y-auto">
        <div class="p-4 space-y-4">
          <!-- Alerts -->
          @if (node!.alerts && node!.alerts.length > 0) {
          <div>
            <h4
              class="text-sm font-semibold text-gray-900 dark:text-white mb-2"
            >
              Alerts
            </h4>
            <div class="space-y-2">
              @for (alert of node!.alerts; track $index) {
              <div
                class="flex items-start gap-2 p-3 rounded-md bg-red-50 dark:bg-red-900/20 border border-red-200 dark:border-red-800"
              >
                <span class="text-red-600 dark:text-red-400">⚠️</span>
                <p class="text-sm text-gray-900 dark:text-white">{{ alert }}</p>
              </div>
              }
            </div>
          </div>
          }

          <!-- Metrics by Family -->
          @for (family of getMetricFamilies(node!); track family) { @let
          familyMetrics = getMetricsForFamily(node!, family); @if
          (familyMetrics.length > 0) {
          <div>
            <h4
              class="text-sm font-semibold text-gray-900 dark:text-white mb-2"
            >
              {{ METRIC_FAMILIES[family].name }}
            </h4>
            <div class="space-y-2">
              @for (metric of familyMetrics; track metric.id) {
              <div class="p-3 rounded-md bg-gray-100 dark:bg-gray-800">
                <div class="flex items-center justify-between">
                  <div>
                    <p
                      class="text-sm font-medium text-gray-900 dark:text-white"
                    >
                      {{ metric.name }}
                    </p>
                    <p class="text-xs text-gray-600 dark:text-gray-400">
                      {{ metric.type }} • SIT: {{ metric.sit }}m @if
                      (metric.isIntegrated) {
                      <span> • Integrated</span>
                      }
                    </p>
                  </div>
                  <div class="text-right">
                    <p
                      class="text-lg font-semibold text-gray-900 dark:text-white"
                    >
                      {{ metric.value.toFixed(2) }}
                    </p>
                    <p class="text-xs text-gray-600 dark:text-gray-400">
                      {{ metric.unit }}
                    </p>
                  </div>
                </div>
              </div>
              }
            </div>
          </div>
          } }

          <!-- Connections -->
          <div>
            <h4
              class="text-sm font-semibold text-gray-900 dark:text-white mb-2"
            >
              Connections
            </h4>
            <div class="grid grid-cols-2 gap-2">
              <div
                class="p-3 rounded-md bg-gray-100 dark:bg-gray-800 text-center"
              >
                <p class="text-xs text-gray-600 dark:text-gray-400 mb-1">
                  Parents
                </p>
                <p class="text-2xl font-bold text-gray-900 dark:text-white">
                  {{ node!.parents.length }}
                </p>
              </div>
              <div
                class="p-3 rounded-md bg-gray-100 dark:bg-gray-800 text-center"
              >
                <p class="text-xs text-gray-600 dark:text-gray-400 mb-1">
                  Children
                </p>
                <p class="text-2xl font-bold text-gray-900 dark:text-white">
                  {{ node!.children.length }}
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    }
  `,
  styles: [
    `
      :host {
        display: contents;
      }
    `,
  ],
})
export class NodeDataPanelComponent {
  @Output() panelClose = new EventEmitter<void>();

  private readonly runtimeState = inject(RuntimeStateService);

  // Expose METRIC_FAMILIES for template
  readonly METRIC_FAMILIES = METRIC_FAMILIES;

  // State from RuntimeStateService
  readonly selectedNode = computed(() => {
    const nodeId = this.runtimeState.selectedNode();
    if (!nodeId) return null;

    const topology = this.runtimeState.topology();
    return (topology?.nodes.get(nodeId) as Node | undefined) || null;
  });

  readonly timeWindow = this.runtimeState.timeWindow;

  close(): void {
    this.runtimeState.setSelectedNode(null);
    this.panelClose.emit();
  }

  getMetricFamily(variableName: string): MetricFamily {
    const name = variableName.toLowerCase();
    if (name.includes('co2') || name.includes('emission')) return 'emissions';
    if (
      name.includes('power') ||
      name.includes('energy') ||
      name.includes('current') ||
      name.includes('voltage')
    )
      return 'energy';
    if (name.includes('temperature') || name.includes('humidity'))
      return 'environmental';
    return 'other';
  }

  getMetricFamilies(node: Node): MetricFamily[] {
    // Get all unique families present in metrics
    const families = new Set<MetricFamily>();
    node.metrics.forEach((metric) => {
      families.add(this.getMetricFamily(metric.variable.name));
    });

    // Sort by order
    return Array.from(families).sort(
      (a, b) => METRIC_FAMILIES[a].order - METRIC_FAMILIES[b].order
    );
  }

  getMetricsForFamily(node: Node, family: MetricFamily): MetricDisplay[] {
    return node.metrics
      .filter((metric) => this.getMetricFamily(metric.variable.name) === family)
      .map((metric) => ({
        id: metric.variable.id,
        name: metric.variable.name,
        type: metric.variable.type,
        sit: metric.variable.sit,
        unit: metric.variable.unit,
        value: metric.value,
        isIntegrated: metric.variable.isIntegrated || false,
      }));
  }
}
